### ISSUE TITLE
No new data since 7-1-18

### ISSUE THREAD

**Issue by Halbatroll** [effinggames/financial-charts#2]
It doesn't look like the USStockAllocationScraper.js script pulls data more recently than from 7-1-18 quarterly update. The data is pulled from the below link. Any idea how to fix this? 'https://fred.stlouisfed.org/graph/fredgraph.xls?chart_type=line&recession_bars=on&log_scales=&bgcolor=%23b3cde7&graph_bgcolor=%23ffffff&fo=Open+Sans&ts=8&tts=8&txtcolor=%23000000&show_legend=yes&show_axis_titles=yes&drp=0&cosd=1945-10-01&coed=2099-01-01&height=378&stacking=&range=&mode=fred&id=NCBEILQ027S_BCNSDODNS_CMDEBT_FGSDODNS_SLGSDODNS_FBCELLQ027S_DODFFSWCMI&transformation=lin_lin_lin_lin_lin_lin_lin&nd=______&ost=-99999_-99999_-99999_-99999_-99999_-99999_-99999&oet=99999_99999_99999_99999_99999_99999_99999&lsv=&lev=&scale=left&line_color=%230000ff&line_style=solid&lw=3&mark_type=none&mw=4&mma=0&fml=((a%2Bf)%2F1000)%2F(((a%2Bf)%2F1000)%2Bb%2Bc%2Bd%2Be%2Bg)&fgst=lin&fgsnd=2007-12-01&fq=Quarterly&fam=avg&vintage_date=&revision_date=&width=630';

**Comment by robgraeber** [comment]
Hey @Halbatroll technically when it says 07/01/2018 that data covers between 07/01/2018 - 09/30/2018 from the Z.1 report of the Fed which came out in Early December 2018. So there'll always be a 3-6 month delay on the Fed data, and it uses the beginning date of the quarter rather than the end.

**Comment by Halbatroll** [comment]
Many thanks for clarifying. Incredible model from philosophicalecon. Thank you for creating this auto-updating chart.
